name: Create and Publish package
on:
  push:
    tags:
      - v*
jobs:
  run-npm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install and build webpack
        run: |
          npm install
          npm run build
      - uses: actions/upload-artifact@main
        with:
          name: webpack artifacts
          path: dist/

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: run-npm-build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build container image
      uses: docker/build-push-action@v2
      with:
        context: .
        tag_with_sha: true
        tag_with_ref: true